#include "postgres.h"
#include "executor/spi.h"

// //#include "executor/executor.h"
// //#include "oid_ext.h"
// #include "pg_config_manual.h"
// //#include "postgres.h"
// #include "postgres_ext.h"
// //#include "utils/nabstime.h"
// //#include "utils/date.h"
// //#include "utils/timestamp.h"
// //#include "fmgr.h"
// //#include "executor/spi.h"

//#include "server/postgres.h"
//#include "elog.h"
//#include "executor/executor.h"
//#include "oid_ext.h"
// #include "c.h"
// #include "pg_config_manual.h"
// #include "postgres_ext.h"
// #include "utils/nabstime.h"
// #include "utils/date.h"
// #include "utils/timestamp.h"
// #include "fmgr.h"
